Update api access for enforced scopes
ucfopen/UDOIT pull request #641
Opened 2021-09-03 20:13 UTC by eriko

While trying to set this up I noticed that the listed scopes that where needed were not accurate. Luckily the error log showed which were being requested.

As a sidenote should I start with the main 3.x version or should I issue the currently listed as released 2.2.8 version if I am just starting?

2021-09-03 20:34 UTC, bagofarms commented
UDOIT 3.x is not "released" open source yet, but will be very soon.  We just have one pull request we're trying to finish first.  All work on UDOIT should be done on the 3.x code, which is in the `main` branch.  I already have a dev branch for UDOIT 3.1.0 (called `dev/v3-1-0`) that all feature PRs should point to.  I'll have someone review this and get it merged in.  Thanks!

2021-09-03 21:32 UTC, webchuckweb requested changes
A few minor updates to the scope URLs.

2021-09-03 21:32 UTC, webchuckweb commented on INSTALL_CANVAS.md
> +    * url:get|/api/v1/courses/:course_id/assignments:id
```suggestion
    * url:GET|/api/v1/courses/:course_id/assignments/:id
```

2021-09-03 21:32 UTC, webchuckweb commented on INSTALL_CANVAS.md
> +    * url:PUT|/api/v1/courses/:course_id/assignments:id
```suggestion
    * url:PUT|/api/v1/courses/:course_id/assignments/:id
```

2021-09-03 21:32 UTC, webchuckweb commented on INSTALL_CANVAS.md
> +    * url:OUT|/api/v1/courses/:id
```suggestion
    * url:PUT|/api/v1/courses/:id
```

2021-09-03 21:32 UTC, webchuckweb commented on INSTALL_CANVAS.md
> +    * ul:GET|/api/v1/courses/:course_id/quizzes/:quiz_id/questions
```suggestion
    * url:GET|/api/v1/courses/:course_id/quizzes/:quiz_id/questions
```

2021-09-03 21:32 UTC, webchuckweb commented on INSTALL_CANVAS.md
> +    * url:GETurl:GET|/api/v1/accounts/:account_id/terms|/api/v1/accounts/:account_id/terms
```suggestion
    * url:GET|/api/v1/accounts/:account_id/terms
```

2021-09-03 21:32 UTC, webchuckweb commented on INSTALL_CANVAS.md
> +    * url:GET|/api/v1/courses/:course_id/modules_id/items
```suggestion
    * url:GET|/api/v1/courses/:course_id/modules/:module_id/items
```

2021-09-03 21:32 UTC, webchuckweb commented on INSTALL_CANVAS.md
> +    * url:GET|/api/v1/courses/:course_id/modules_id/items/:id
```suggestion
    * url:GET|/api/v1/courses/:course_id/modules/:module_id/items/:id
```

2021-09-07 20:03 UTC, AlanFCMV requested changes
I tested this and you are still missing a scope on the list. Specifically:
- url:GET|/api/v1/accounts/:account_id/sub_accounts
Additionally, the following scope appears to not be necessary:
- url:POST|/api/v1/courses/:course_id/quizzes/:quiz_id/questions u

2021-09-07 20:17 UTC, eriko commented on INSTALL_CANVAS.md
> +    * url:POST|/api/v1/courses_id/files
"GET /authorize/check?error=invalid_scope&error_description=A requested scope is invalid, unknown, malformed, or exceeds the scope granted by the resource owner. The following scopes were requested, but not granted:
...
url:POST|/api/v1/courses/:course_id/files
...
Was in the error message I extracted from the logs. Was it removed in the last few days?

2021-09-07 20:22 UTC, AlanFCMV commented on INSTALL_CANVAS.md
> +    * url:POST|/api/v1/courses_id/files
This is just a typo correction. It is currently listed as `url:POST|/api/v1/courses_id/files` when it should be `url:POST|/api/v1/courses/:course_id/files`

2021-09-07 20:24 UTC, eriko commented on INSTALL_CANVAS.md
> +    * url:POST|/api/v1/courses_id/files
An another 'I can not typo' error.

2021-09-08 12:10 UTC, AlanFCMV commented
Please add `url:GET|/api/v1/accounts/:account_id/sub_accounts` under accounts as well.

2021-09-08 15:20 UTC, eriko commented
url:GET|/api/v1/accounts/:account_id/sub_accounts 
added

2021-09-08 18:54 UTC, AlanFCMV approved these changes

2021-09-09 19:09 UTC, cidilabs approved these changes

2021-09-09 20:32 UTC, merged