fixing issue unresolve bug and adding concept of scanIssue/decreased …
ucfopen/UDOIT pull request #873
Opened 2022-12-19 17:26 UTC by atarisafari

…amount of intial data on issue load

Fixes: https://github.com/ucfopen/UDOIT/issues/867

Adds concept of loading less issue data on initial app load, but scanning for further issue data when the issue is opened in the modal.

2022-12-20 22:21 UTC, taheralfayad commented
Whenever I try to run UDOIT on the [cidilabs:fixUnresolveBug](cidilabs:fixUnresolveBug) branch, I, for some reason, am not able access any of the issues, and PHP just returns a 404 error.

<img width="1014" alt="Screen Shot 2022-12-20 at 11 03 27 AM" src="https://user-images.githubusercontent.com/93749906/208777814-84856415-6e72-468a-a4ca-1aad1ded801b.png">

<img width="747" alt="Screen Shot 2022-12-20 at 11 03 36 AM" src="https://user-images.githubusercontent.com/93749906/208777833-62f5e995-157a-4e14-9e58-62633bdb2d2c.png">

2022-12-21 14:55 UTC, atarisafari commented
@taheralfayad I'll take a look, thanks for pointing that out.

2023-05-10 19:11 UTC, taheralfayad commented on assets/js/Components/UfixitModal.js
> +      UfixitForm = ufixitService.returnIssueForm(activeIssue)
I cannot find `ufixitService` anywhere in the React files, only on this line. Returns an error:
```
Uncaught (in promise) ReferenceError: ufixitService is not defined
    at a.value (app.js:252:268294)
    at Pa (app.js:377:69887)
    at Na (app.js:377:69682)
    at gs (app.js:377:105481)
    at cl (app.js:377:96728)
    at sl (app.js:377:96653)
    at Zs (app.js:377:93683)
    at app.js:377:45325
    at t.unstable_runWithPriority (app.js:11:3844)
    at Fi (app.js:377:45034)
```

2023-06-20 21:22 UTC, dmols requested changes
Can confirm that like @taheralfayad, I also get the infinite loop upon clicking on any issue, as well as a 404 error in the logs.

2023-06-22 21:33 UTC, dmols commented
Hey @atarisafari, it's been a while since this PR has had any updates but have you by any chance been able to test the issue @taheralfayad and I were having, regarding the immediate infinite loading screen? I'm unable to test the branch as is. Thank you!

2024-07-25 19:54 UTC, dmols commented
Hey @atarisafari, thank you for working on this issue, though I'm not able to test the fix since @taheralfayad and I get an infinite loading screen and 404 error when we try to load issues on UFIXIT. I'll close this and likely make another branch/PR in the future to look into the issue closer. Please let me know if you'd like to troubleshoot the roadblock on your branch! I'd be happy to assist and reopen the PR if we can get past that.

2024-07-25 19:54 UTC, closed without merging